name: Build and Release TimeLink

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build and publish (macOS)
      if: matrix.platform == 'mac'
      run: npm run build-publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_IDENTITY_AUTO_DISCOVERY: false
    
    - name: Build and publish (Windows)
      if: matrix.platform == 'win'
      run: npm run build-publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and publish (Linux)
      if: matrix.platform == 'linux'
      run: npm run build-publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}