name: Build/release

on:
  push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token (automatically provided); no need to set this secret yourself
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # If this push is a tag starting with “v” (e.g. “v1.0.0”), perform a Release
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}