name: Build and Release Electron App

on:
  push:
    # Only run this workflow when a new Git tag matching v*.*.* is pushed
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # Allows the action to create and upload release assets

jobs:
  build-and-release:
    runs-on: macos-latest

    env:
      NODE_ENV: production
      ELECTRON_BUILDER_CACHE: ${{ runner.temp }}/electron-builder-cache

    steps:
      # ───────────────────────────────────────────────────────────────────
      # 1) Check out the repository (with full history and tags)
      # ───────────────────────────────────────────────────────────────────
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ───────────────────────────────────────────────────────────────────
      # 2) Set up Node.js and enable npm caching
      # ───────────────────────────────────────────────────────────────────
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # ───────────────────────────────────────────────────────────────────
      # 3) Install dependencies
      # ───────────────────────────────────────────────────────────────────
      - name: Install dependencies
        run: npm ci

      # ───────────────────────────────────────────────────────────────────
      # 4) Ensure package.json version matches the Git tag
      # ───────────────────────────────────────────────────────────────────
      - name: Ensure version matches Git tag
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PKG_VERSION=$(node -pe "require('./package.json').version")
          echo "Git tag: $TAG"
          echo "package.json version: $PKG_VERSION"
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "Error: Git tag ($TAG) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi

      # ───────────────────────────────────────────────────────────────────
      # 5) Build and publish with electron-builder
      # ───────────────────────────────────────────────────────────────────
      - name: Build and Publish with electron-builder
        id: build_and_publish
        uses: electron-builder/electron-builder-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # (Optional) If you only want to build/publish for mac:
          # targets: mac
          #
          # (Optional) Once you’re ready to code-sign on macOS, you can uncomment:
          # mac-sign: true
          # mac-codesign-identity: "Developer ID Application: Your Name (TEAMID)"